version: '3'
services:
    database:
        build: ./WEB(BE)/database/
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: 'miliroutine_db'
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
