version: '3'
services:
  database:
    container_name: database
    build: ./db
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: '2022MySQL!@'
      MYSQL_DATABASE: 'miliroutine_db'
  frontend:
    container_name: frontend
    build: ./WEB(FE)
    volumes:
      - './WEB(FE)/:/app'
      - '/app/node_modules'
    expose:
      - 5173
    networks:
      - miliroutine
  backend:
    container_name: backend
    build: ./WEB(BE)
    restart: 'on-failure'
    ports:
      - '8080:8080'
    volumes:
      - './WEB(BE):/app'
      - '/app/node_modules'
    stdin_open: true
    tty: true
    depends_on:
      - database
  ai:
    container_name: ai
    build: ./AI
    ports:
      - '8081:8081'
    volumes:
      - './AI:/app'
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: 'on-failure'
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./WEB(FE)/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

networks:
  miliroutine:
    driver: bridge
